// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int IdMarca { get; set; }

    public int IdModelo { get; set; }

    public decimal Precio { get; set; }

    public float Peso { get; set; }

    public virtual Marca IdMarcaNavigation { get; set; }

    public virtual Modelo IdModeloNavigation { get; set; }

    public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; } = new List<PedidoDetalle>();
}